const NAMESPACE = "twitch-embed-player-proxy";
const UPDATE = { UpdateState: "UPDATE_STATE" };
const VIDEO_TYPE = { VideoWithChat: "video-with-chat", Video: "video" };
const STATUS = {
  AUTHENTICATE: "authenticate",
  VIDEO_READY: "video.ready",
  VIDEO_PLAY: "video.play",
  VIDEO_PAUSE: "video.pause",
  CAPTIONS: "captions",
  ENDED: "ended",
  ERROR: "error",
  ONLINE: "online",
  OFFLINE: "offline",
  PAUSE: "pause",
  PLAY: "play",
  PLAYBACK_BLOCKED: "playbackBlocked",
  PLAYING: "playing",
  READY: "ready",
};
const COMMAND = {
  0: "DisableCaptions",
  1: "EnableCaptions",
  2: "Pause",
  3: "Play",
  4: "Seek",
  5: "SetChannel",
  6: "SetChannelID",
  7: "SetCollection",
  8: "SetQuality",
  9: "SetVideo",
  10: "SetMuted",
  11: "SetVolume",
  DisableCaptions: 0,
  EnableCaptions: 1,
  Pause: 2,
  Play: 3,
  Seek: 4,
  SetChannel: 5,
  SetChannelID: 6,
  SetCollection: 7,
  SetQuality: 8,
  SetVideo: 9,
  SetMuted: 10,
  SetVolume: 11,
};
const ERROR_CODE = {
  1: "GeoBlocked",
  2: "UnsupportedDevice",
  3: "AnonymizerBlocked",
  4: "CellularNetworkProhibited",
  5: "UnauthorizationEntitlements",
  6: "VodRestricted",
  509: "LVSCCUCap",
  1000: "Aborted",
  2000: "Network",
  2001: "CCUCapReached",
  3000: "Decode",
  4000: "FormatNotSupported",
  5000: "ContentNotAvailable",
  6000: "RendererNotAvailable",
  7004: "SafariUnsupportedDevice",
  8001: "Fatal",
  8002: "Offline",
  8003: "FatalAuth",
  8004: "WarnAuth",
  GeoBlocked: 1,
  UnsupportedDevice: 2,
  AnonymizerBlocked: 3,
  CellularNetworkProhibited: 4,
  UnauthorizationEntitlements: 5,
  VodRestricted: 6,
  LVSCCUCap: 509,
  Aborted: 1000,
  Network: 2000,
  CCUCapReached: 2001,
  Decode: 3000,
  FormatNotSupported: 4000,
  ContentNotAvailable: 5000,
  RendererNotAvailable: 6000,
  SafariUnsupportedDevice: 7004,
  Fatal: 8001,
  FatalAuth: 8003,
  Offline: 8002,
  WarnAuth: 8004,
};
const RESTRICTION = {
  PREMIUM_CONTENT_RESTRICTED: "PREMIUM_CONTENT",
  VOD_RESTRICTED: "vod_manifest_restricted",
};

const PLAYBACK = {
  IDLE: "Idle",
  READY: "Ready",
  BUFFERING: "Buffering",
  PLAYING: "Playing",
  ENDED: "Ended",
};

const PLAYER_STATE = {
  channelName: "",
  channelID: "",
  collectionID: "",
  currentTime: 0,
  duration: 0,
  muted: !1,
  playback: PLAYBACK.IDLE,
  quality: "",
  qualitiesAvailable: [],
  stats: {
    videoStats: {
      backendVersion: "",
      bufferSize: 0,
      codecs: "",
      displayResolution: "",
      fps: 0,
      hlsLatencyBroadcaster: 0,
      latencyMode: "",
      playbackRate: 0,
      skippedFrames: 0,
      videoResolution: "",
    },
  },
  videoID: "",
  volume: 0,
  ended: !1,
};

export {
  NAMESPACE,
  UPDATE,
  VIDEO_TYPE,
  STATUS,
  COMMAND,
  ERROR_CODE,
  RESTRICTION,
  PLAYBACK,
  PLAYER_STATE,
};
